---
version: '3'
services:

  consul:
    image: consul:latest
    ports:
      - "8501:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true

  consul-registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ["consul://consul:8500"]
    depends_on:
      - consul

  emojify-facebox:
    image: "machinebox/facebox"
    ports:
      - "8080:8080"
    environment:
      - MB_KEY=${MB_KEY}
      - SERVICE_NAME=emojify-facebox
      - SERVICE_8080_CHECK_HTTP=/healthz
      - SERVICE_8080_CHECK_INTERVAL=15s
      - SERVICE_8080_CHECK_TIMEOUTL=1s

  emojify-facebox-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-facebox"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-facebox',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-facebox:8443',
      '-service-addr', 'localhost:8080',
      '-register',
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-cache:
    image: "nicholasjackson/emojify-cache:latest"
    ports:
      - "9001:9001"
    environment:
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=9001
      - HEALTH_BIND_ADDRESS=0.0.0.0
      - HEALTH_BIND_PORT=9002
      - SERVICE_NAME=emojify-cache
      - SERVICE_9001_CHECK_TCP=true
      - SERVICE_9001_CHECK_INTERVAL=15s
      - SERVICE_9001_CHECK_TIMEOUT=1s

  emojify-cache-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-cache"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-cache',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-cache:8443',
      '-service-addr', 'localhost:9001',
      '-register',
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul
